# Generated by Django 3.1.5 on 2021-01-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cantidaDisponible',
            field=models.IntegerField(),
        ),
    ]
