# Generated by Django 3.1.5 on 2021-01-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210113_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cantidaDisponible',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
