# Generated by Django 3.1.5 on 2021-01-13 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20210113_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='cantidaDisponible',
        ),
    ]
