# Generated by Django 3.1.5 on 2021-01-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_ventas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(auto_created=True, max_length=3, primary_key=True, serialize=False),
        ),
    ]
