# Generated by Django 3.1.5 on 2021-01-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20210113_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
