# Generated by Django 3.1.5 on 2021-01-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_auto_20210113_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='montoVenta',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
