# Generated by Django 3.1.5 on 2021-01-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_remove_ventas_montoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='Montoxd',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
    ]
