# Generated by Django 3.1.5 on 2021-01-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_auto_20210113_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='Montoxd',
        ),
        migrations.AddField(
            model_name='ventas',
            name='monto',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
