# Generated by Django 3.1.5 on 2021-01-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_auto_20210114_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='idVenta',
        ),
        migrations.AddField(
            model_name='ventas',
            name='venta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.productos'),
        ),
    ]
